baseURL = 'https://0xca7.github.io/'
languageCode = 'en-us'
title = '0xca7'
theme = "xmin"
[params]
    description = "RE, Programming, Embedded Systems, Cybersecurity"
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts"
        weight = 2
    [[menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "/notes"
        weight = 3
    [[menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/0xca7"
        weight = 4
    [[menu.main]]
        identifier = "youtube"
        name = "Youtube"
        url = "https://www.youtube.com/channel/UCYKUCM--rF5yC0c1a1rTgBQ"
        weight = 5
