baseURL = 'https://0xca7.github.io/'
languageCode = 'en-us'
title = '0xca7'
theme = "xmin"
[params]
    description = "RE, Programming, Embedded Systems, Cybersecurity"
[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/0xca7/"},
      {Name = "YouTube", URL = "https://www.youtube.com/channel/UCYKUCM--rF5yC0c1a1rTgBQ"},
      {Name = "Blog", URL = "/posts"},
  ]
